name: Developer_Pull_Request_CI
on:
  push:
    branches:
      - 'main'

jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Unit Tests
        run: echo Unit Tests
      - name: Integration Testing
        run: echo Integration Testing
      - name: SAST Scans
        run: echo sast scans
      - name: secrets in Source Code
        run: echo secrets in source code
      - name: Code Quality
        run: echo code Quality