name: Developer_Branch_CI
on: [workflow_call]

jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit Tests
        run: echo Unit Tests
      - name: Integration Testing
        run: echo Integration Testing
      - name: Code Quality
        run: echo code Quality