name: Developer_Pull_Request
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true

jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit Tests
        run: echo Unit Tests
      - name: Integration Testing
        run: echo Integration Testing
      - name: SAST Scans
        run: echo sast scans
      - name: secrets in Source Code
        run: echo secrets in source code
      - name: Code Quality
        run: echo code Quality